#!/bin/bash
# =============================================================================
# LumiFarm — Blue/Green Zero-Downtime Deploy Script
# =============================================================================
# Usage:
#   bash deploy/deploy.sh                        → deploy both services
#   bash deploy/deploy.sh backend                → deploy backend only
#   bash deploy/deploy.sh frontend               → deploy frontend only
#   bash deploy/deploy.sh rollback               → rollback both services
#   bash deploy/deploy.sh rollback backend       → rollback backend only
#   bash deploy/deploy.sh rollback frontend      → rollback frontend only
# =============================================================================

set -euo pipefail

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEPLOY_DIR="$SCRIPT_DIR"

BACKEND_STATE_FILE="$DEPLOY_DIR/.active-backend"
FRONTEND_STATE_FILE="$DEPLOY_DIR/.active-frontend"
NGINX_UPSTREAM_CONF="/etc/nginx/conf.d/lumifarm-upstreams.conf"

# ── Port map ──────────────────────────────────────────────────────────────────
BACKEND_BLUE_PORT=3401
BACKEND_GREEN_PORT=3402
FRONTEND_BLUE_PORT=4001
FRONTEND_GREEN_PORT=4002

# ── Health check settings ─────────────────────────────────────────────────────
HEALTH_RETRIES=30
HEALTH_INTERVAL=5

# ─────────────────────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────────────────────

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

die() {
  log "FATAL: $*"
  exit 1
}

require_root() {
  if [ "$EUID" -ne 0 ]; then
    die "This script must be run as root (needed to reload nginx)"
  fi
}

# Returns the currently active color for a service (defaults to "green"
# so that the very first deploy will choose "blue" as the next color).
get_active() {
  local state_file="$1"
  if [ -f "$state_file" ]; then
    cat "$state_file"
  else
    echo "green"
  fi
}

next_color() {
  if [ "$1" = "blue" ]; then echo "green"; else echo "blue"; fi
}

backend_port_for() {
  if [ "$1" = "blue" ]; then echo "$BACKEND_BLUE_PORT"; else echo "$BACKEND_GREEN_PORT"; fi
}

frontend_port_for() {
  if [ "$1" = "blue" ]; then echo "$FRONTEND_BLUE_PORT"; else echo "$FRONTEND_GREEN_PORT"; fi
}

# Atomically rewrite the nginx upstream config and reload nginx
write_upstreams() {
  local backend_port="$1"
  local frontend_port="$2"
  local tmp_file
  tmp_file="$(mktemp /tmp/lumifarm-upstreams.XXXXXX.conf)"

  cat > "$tmp_file" << NGINX_CONF
# Auto-generated by deploy.sh — do not edit manually
upstream lumifarm_backend {
    server 127.0.0.1:${backend_port};
}

upstream lumifarm_frontend {
    server 127.0.0.1:${frontend_port};
}
NGINX_CONF

  mv "$tmp_file" "$NGINX_UPSTREAM_CONF"
  nginx -t -q && nginx -s reload
  log "Nginx reloaded → backend:${backend_port}  frontend:${frontend_port}"
}

# Poll a URL until it responds 200 or retries are exhausted
health_check() {
  local url="$1"
  local label="$2"

  log "Health-checking ${label} at ${url} ..."
  local i=1
  while [ "$i" -le "$HEALTH_RETRIES" ]; do
    if curl -sf --max-time 5 "$url" > /dev/null 2>&1; then
      log "${label} is healthy (attempt ${i}/${HEALTH_RETRIES})"
      return 0
    fi
    log "  attempt ${i}/${HEALTH_RETRIES} — waiting ${HEALTH_INTERVAL}s ..."
    sleep "$HEALTH_INTERVAL"
    i=$((i + 1))
  done

  log "ERROR: ${label} failed health check after ${HEALTH_RETRIES} attempts"
  return 1
}

# ─────────────────────────────────────────────────────────────────────────────
# Deploy backend
# ─────────────────────────────────────────────────────────────────────────────
deploy_backend() {
  local cur_color next_col cur_port next_port fe_port

  cur_color="$(get_active "$BACKEND_STATE_FILE")"
  next_col="$(next_color "$cur_color")"
  cur_port="$(backend_port_for "$cur_color")"
  next_port="$(backend_port_for "$next_col")"
  fe_port="$(frontend_port_for "$(get_active "$FRONTEND_STATE_FILE")")"

  log "━━━ Backend deploy: ${cur_color}:${cur_port} → ${next_col}:${next_port}"

  cd "$PROJECT_ROOT"

  log "Building lumifarm-backend:${next_col} ..."
  docker compose -f deploy/docker-compose.${next_col}.yml build lumifarm-backend-${next_col}

  log "Starting lumifarm-backend-${next_col} ..."
  docker compose -f deploy/docker-compose.${next_col}.yml up -d lumifarm-backend-${next_col}

  if ! health_check "http://localhost:${next_port}/docs" "backend-${next_col}"; then
    log "Rolling back: stopping lumifarm-backend-${next_col}"
    docker compose -f deploy/docker-compose.${next_col}.yml stop lumifarm-backend-${next_col} || true
    die "Backend deploy failed. Old container (${cur_color}) is still serving traffic."
  fi

  write_upstreams "$next_port" "$fe_port"
  echo "$next_col" > "$BACKEND_STATE_FILE"

  log "Stopping old container lumifarm-backend-${cur_color} ..."
  docker compose -f deploy/docker-compose.${cur_color}.yml stop lumifarm-backend-${cur_color} 2>/dev/null || true

  log "Backend deploy complete — active: ${next_col} (port ${next_port})"
}

# ─────────────────────────────────────────────────────────────────────────────
# Deploy frontend
# ─────────────────────────────────────────────────────────────────────────────
deploy_frontend() {
  local cur_color next_col cur_port next_port be_port

  cur_color="$(get_active "$FRONTEND_STATE_FILE")"
  next_col="$(next_color "$cur_color")"
  cur_port="$(frontend_port_for "$cur_color")"
  next_port="$(frontend_port_for "$next_col")"
  be_port="$(backend_port_for "$(get_active "$BACKEND_STATE_FILE")")"

  log "━━━ Frontend deploy: ${cur_color}:${cur_port} → ${next_col}:${next_port}"

  cd "$PROJECT_ROOT"

  log "Building lumifarm-frontend:${next_col} ..."
  docker compose -f deploy/docker-compose.${next_col}.yml build lumifarm-frontend-${next_col}

  log "Starting lumifarm-frontend-${next_col} ..."
  docker compose -f deploy/docker-compose.${next_col}.yml up -d lumifarm-frontend-${next_col}

  if ! health_check "http://localhost:${next_port}/" "frontend-${next_col}"; then
    log "Rolling back: stopping lumifarm-frontend-${next_col}"
    docker compose -f deploy/docker-compose.${next_col}.yml stop lumifarm-frontend-${next_col} || true
    die "Frontend deploy failed. Old container (${cur_color}) is still serving traffic."
  fi

  write_upstreams "$be_port" "$next_port"
  echo "$next_col" > "$FRONTEND_STATE_FILE"

  log "Stopping old container lumifarm-frontend-${cur_color} ..."
  docker compose -f deploy/docker-compose.${cur_color}.yml stop lumifarm-frontend-${cur_color} 2>/dev/null || true

  log "Frontend deploy complete — active: ${next_col} (port ${next_port})"
}

# ─────────────────────────────────────────────────────────────────────────────
# Rollback a service to its previous (stopped) container
# ─────────────────────────────────────────────────────────────────────────────
rollback_backend() {
  local cur_color prev_color cur_port prev_port fe_port

  cur_color="$(get_active "$BACKEND_STATE_FILE")"
  prev_color="$(next_color "$cur_color")"   # previous = the "other" color
  cur_port="$(backend_port_for "$cur_color")"
  prev_port="$(backend_port_for "$prev_color")"
  fe_port="$(frontend_port_for "$(get_active "$FRONTEND_STATE_FILE")")"

  log "━━━ Backend rollback: ${cur_color} → ${prev_color}"

  if ! docker container inspect "lumifarm-backend-${prev_color}" > /dev/null 2>&1; then
    die "Container lumifarm-backend-${prev_color} not found. Cannot rollback (was it ever deployed?)."
  fi

  cd "$PROJECT_ROOT"
  docker compose -f deploy/docker-compose.${prev_color}.yml start lumifarm-backend-${prev_color}

  if ! health_check "http://localhost:${prev_port}/docs" "backend-${prev_color}"; then
    die "Rollback target (${prev_color}) is also unhealthy. Manual intervention required."
  fi

  write_upstreams "$prev_port" "$fe_port"
  echo "$prev_color" > "$BACKEND_STATE_FILE"

  docker compose -f deploy/docker-compose.${cur_color}.yml stop lumifarm-backend-${cur_color} 2>/dev/null || true
  log "Backend rolled back to ${prev_color} (port ${prev_port})"
}

rollback_frontend() {
  local cur_color prev_color cur_port prev_port be_port

  cur_color="$(get_active "$FRONTEND_STATE_FILE")"
  prev_color="$(next_color "$cur_color")"
  cur_port="$(frontend_port_for "$cur_color")"
  prev_port="$(frontend_port_for "$prev_color")"
  be_port="$(backend_port_for "$(get_active "$BACKEND_STATE_FILE")")"

  log "━━━ Frontend rollback: ${cur_color} → ${prev_color}"

  if ! docker container inspect "lumifarm-frontend-${prev_color}" > /dev/null 2>&1; then
    die "Container lumifarm-frontend-${prev_color} not found. Cannot rollback."
  fi

  cd "$PROJECT_ROOT"
  docker compose -f deploy/docker-compose.${prev_color}.yml start lumifarm-frontend-${prev_color}

  if ! health_check "http://localhost:${prev_port}/" "frontend-${prev_color}"; then
    die "Rollback target (${prev_color}) is also unhealthy. Manual intervention required."
  fi

  write_upstreams "$be_port" "$prev_port"
  echo "$prev_color" > "$FRONTEND_STATE_FILE"

  docker compose -f deploy/docker-compose.${cur_color}.yml stop lumifarm-frontend-${cur_color} 2>/dev/null || true
  log "Frontend rolled back to ${prev_color} (port ${prev_port})"
}

# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────
require_root

CMD="${1:-both}"
SUBCMD="${2:-both}"

log "══════════════════════════════════════════"
log " LumiFarm Deploy  —  cmd: ${CMD} ${SUBCMD}"
log "══════════════════════════════════════════"

# Pull latest code (skip for rollback)
if [ "$CMD" != "rollback" ]; then
  cd "$PROJECT_ROOT"
  log "Pulling latest code from origin/main ..."
  # Uses deploy key configured in ~/.ssh/config (Host: github-lumifarm)
  GIT_SSH_COMMAND="ssh -i /root/.ssh/lumifarm_deploy -o StrictHostKeyChecking=no" \
    git pull origin main

  # Sync nginx site configs from repo to server (picks up any config changes)
  log "Syncing nginx site configs ..."
  cp "$PROJECT_ROOT/deploy/nginx/farmapi.lumina360.tech" /etc/nginx/sites-available/farmapi.lumina360.tech
  cp "$PROJECT_ROOT/deploy/nginx/farm.lumina360.tech"    /etc/nginx/sites-available/farm.lumina360.tech
  cp "$PROJECT_ROOT/deploy/nginx/lumifarm-upstreams.conf" /etc/nginx/conf.d/lumifarm-upstreams.conf
fi

case "$CMD" in
  backend)
    deploy_backend
    ;;

  frontend)
    deploy_frontend
    ;;

  rollback)
    case "$SUBCMD" in
      backend)  rollback_backend  ;;
      frontend) rollback_frontend ;;
      both)
        rollback_backend
        rollback_frontend
        ;;
      *)
        die "Unknown rollback target: ${SUBCMD}. Use: backend | frontend | both"
        ;;
    esac
    ;;

  both)
    deploy_backend
    deploy_frontend
    ;;

  *)
    echo "Usage: $0 [backend|frontend|both|rollback [backend|frontend|both]]"
    exit 1
    ;;
esac

log "══════════════════════════════════════════"
log " Deploy finished successfully"
log "══════════════════════════════════════════"
