#!/bin/bash
# Quick restart guide for Lumifarm

echo "=========================================="
echo "LUMIFARM FARM CREATION FIX - FINAL STEPS"
echo "=========================================="
echo ""
echo "✓ Database setup: COMPLETE"
echo "  - Lumifarm tenant created"
echo "  - Admin user linked to tenant"
echo ""
echo "⚠ YOUR CURRENT ISSUE:"
echo "  Your JWT token was issued BEFORE the tenant was linked."
echo "  It contains empty tenantIds and tenantId values."
echo ""
echo "✓ SOLUTION: Log out and log back in"
echo ""
echo "STEPS:"
echo "1. In your browser, go to http://localhost:4200"
echo "2. Click the logout button (top right corner, user menu)"
echo "3. Log in again with:"
echo "   Email:    admin@lumifarm.co.ke"
echo "   Password: Lumifarm@2026"
echo "4. After login, you'll get a NEW JWT token with tenant context"
echo "5. Try creating a farm - it should work now!"
echo ""
echo "VERIFICATION:"
echo "After login, open DevTools (F12) → Console and run:"
echo "  localStorage.getItem('rentium_active_tenant')"
echo "Should show: 69c6c13f320cd77d33fc701f"
echo ""
echo "=========================================="
